### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by hemant17** [laravolt/avatar#105]
I am getting error of - Class name must be a valid object or a string 
when i try to use it in blade.php

**Comment by sectorf8** [comment]
Same here :(

**Comment by uyab** [comment]
Did you override the configuration?
Could you provide sample code?
Could you provide the complete error message + stack trace?

**Comment by shohanean** [comment]
Same Error!

**Comment by shohanean** [comment]
Can not do anything at controller, not at blade. Any suggestions?

**Comment by uyab** [comment]
@shohanean please provide some code snippet so I can suggests what is wrong

**Comment by hemant17** [comment]
> @shohanean please provide some code snippet so I can suggests what is wrong

there is nothing special code snippet we just following the simple install step -  https://github.com/laravolt/avatar#output-as-base64
it just shows that error. with default laravel install and with installed.

**Comment by uyab** [comment]
If so, could yo provide the full stack trace of the error here?

**Comment by shohanean** [comment]
Yes nothing special code

**Comment by uyab** [comment]
@shohanean full error message please 😄

**Comment by shohanean** [comment]
I just require the package, then published the vendor.
In my controller which is Called ProfileController.php I added
`Use use Avatar;`
Then in index method I just tried to echo like this:
`echo Avatar::create('Joko Widodo')->toBase64();`
Then the error came out!

**Comment by shohanean** [comment]
Error
Class name must be a valid object or a string

**Comment by shohanean** [comment]
In line:
vendor\laravolt\avatar\src\ServiceProvider.php:38

**Comment by uyab** [comment]
So it is related to config file:

```php
  // Initial generator class
    'generator' => \Laravolt\Avatar\Generator\DefaultGenerator::class,
```

Could you confirm that you have that entry in config/laravolt/avatar.php ?

Or, you can check using `php artisan tinker`, what is the output of the following code:
`config(laravolt.avatar.generator)`

**Comment by dieume-n** [comment]
The output of ```php config('laravolt.avatar.generator') ``` is null

**Comment by dieume-n** [comment]
Solved by running ``` php artisan config:cache ``` to clear and rebuild the configuration cache

**Comment by kb6673** [comment]
I solved this just like @dieume-n .

Perhaps the documentation should remind us to rebuild the config cache.
