### ISSUE TITLE
is there a way to create an avatar out of a number ?

### ISSUE THREAD

**Issue by ctf0** [laravolt/avatar#107]

**Comment by uyab** [comment]
I think it is already have this functionality by default, did you try it?

**Comment by ctf0** [comment]
yes, and i got this error
```
Trying to access array offset on value of type int
@ vendor/laravolt/avatar/src/Avatar.php:419
```

**Comment by uyab** [comment]
What about pass string "123" instead of int 123 ? Is it possible to do it in your code?

**Comment by uyab** [comment]
Or you can cast the number into string:
```php
Avatar::create((string)135)->toBase64();
```

**Comment by ctf0** [comment]
> Avatar::create((string)135)->toBase64();

yeah that did work, thanx for the quick help.
