### ISSUE TITLE
How heavy is the process?

### ISSUE THREAD

**Issue by omidMolaverdi** [laravolt/avatar#108]
I am thinking of using avatar creating on fly. I have a max of 1000 per user per refresh. How heavy is this process? do you suggest storing the images? (there is a downside to it as I have to recreate the images per user edit +a lot of little files on disk)

**Comment by omidMolaverdi** [comment]
Hi, 

is there any update on this thread?

**Comment by uyab** [comment]
Hi, if you generate base64 and have cache enabled, than image generation only happen once.
