### ISSUE TITLE
Right to left script support

### ISSUE THREAD

**Issue by omidMolaverdi** [laravolt/avatar#109]
Thanks for the great package. I know that with proper fonts, the package supports right-2-left (R2L) scripts however the direction of letters on the photo is not right. Github issue does not allow me to upload a photo but the concept is easy to imagine. Let the R2L name is **wonS nhoJ** (from right to left it is John snow), then the current implementation of the picture would have JS in it that is read as Snow John because of the R2L nature of the language.  I can temporarily suppress the problem by allowing only one letter of the word but could be much better to support the right direction of the script.

**Comment by omidMolaverdi** [comment]
Hi, 

is there any update on this thread?

**Comment by uyab** [comment]
Sorry for late response. I'm not familiar with RTL, but if I understand you correctly, we just need to reverse the initials.

**normal -> RTL**
BHW       -> WHB
JS           -> SJ
A              -> A

**Comment by omidMolaverdi** [comment]
@uyab yes that is right!

**Comment by abdullahessam** [comment]
@uyab  any update about the RTL vesion ?

**Comment by uyab** [comment]
Hi @abdullahessam, would you like to check `dev-master`, add `"rtl" => true` to your `config/laravolt/avatar.php` and check if its working?

**Comment by omidMolaverdi** [comment]
wow well done

**Comment by abdullahessam** [comment]
thank you @uyab  for this update i think you did n't the case well so here is an example for the problem my name is 
abdullah essam so the expected letters is AE and this is happen correct but in RTL language like arabic for example 
محمد عبدالله  the expected letters should be  م ع   but the actual is ع م  so we just need to auto support the rtl language i have no idea what well the users input in English or in arabic 
any way thank you for your effort and really appreciate  it

**Comment by uyab** [comment]
Here is sample output using `"rtl" => true` and RTL font Amiri:
![image](https://user-images.githubusercontent.com/149716/107794268-cea81080-6d89-11eb-8af2-81eb11259dbc.png)

Any screenshot or live demo are welcome, I still don't get where the problem is 🤔 

Font: https://fonts.google.com/specimen/Amiri
