### ISSUE TITLE
Laravel 8.x Support

### ISSUE THREAD

**Issue by danpalmieri** [laravolt/avatar#112]
Any plans? ;-)
Thank you in advance!

**Comment by neoteknic** [comment]
Maybe just need to merge my PR, it's only dependencies updates.

**Comment by tumichnix** [comment]
Please merge this PR #110

**Comment by uyab** [comment]
https://github.com/laravolt/avatar/releases/tag/4.0.0

Avatar ready! Build something amazing 🥳
