### ISSUE TITLE
Configurable place to place the assets of fonts..

### ISSUE THREAD

**Issue by renege** [laravolt/avatar#12]
@laravolt the folder now in resources isn't pretty.

**Comment by uyab** [comment]
Any suggestion ?

**Comment by renege** [comment]
Path ```'resources/laravolt/avatar/fonts/'``` in config file?

**Comment by uyab** [comment]
Hi @renege, if there is a better location?

**Comment by renege** [comment]
@uyab most packages do it in /resources/assets/vendor/* but if you make it configurable via config file then it's all up to the user himself

**Comment by uyab** [comment]
@ctf0 why you need the fonts to be publishable?
