### ISSUE TITLE
Serialization of 'GdImage' is not allowed

### ISSUE THREAD

**Issue by ctf0** [laravolt/avatar#124]
after latest release, i started getting this error.

its cuzed by https://github.com/laravolt/avatar/blob/525051f0da5b887ed8aac247ca6b59693416c1dc/src/Avatar.php#L191

when using redis at https://github.com/laravel/framework/blob/4d37befac3a43e27e75725fd46f5b43de2bd7c53/src/Illuminate/Cache/RedisStore.php#L325

however the issue is not related only to redis, even with file store we can get the same issue.

**Comment by ctf0** [comment]
@uyab is it possible to release an alpha version without the cache line ?

**Comment by dionysiosarvanitis** [comment]
@ctf0 you can do `composer require laravolt/avatar:4.0.0` instead.

**Comment by ctf0** [comment]
@dionysiosarvanitis  ah yes, totally forgot about this one, thanx for the heads up

**Comment by uyab** [comment]
Should fixed in 4.1.1
