### ISSUE TITLE
The background of the generated avatar is all white, how to solve it?

### ISSUE THREAD

**Issue by JeffreyBool** [laravolt/avatar#125]
The background of the generated avatar is all white, how to solve it?

**Comment by uyab** [comment]
Please provide some screenshot + sample code

**Comment by brioapp** [comment]
same here, always light gray background. laravel 8

**Comment by uyab** [comment]
@brioapp could you provide sample code ?

**Comment by joerjoers** [comment]
### Sample Screenshot
![image](https://user-images.githubusercontent.com/4877880/114150871-1e9cf100-994f-11eb-8fa7-c10cdff1c82d.png)

### Code Snippet
`$avatarAPI = new Avatar();`
`$avatar = $avatarAPI->create($name)->setTheme('pastel')->save($fileName, 100);`

`Storage::put('avatars/' . $fileName, $avatar);`

### Environment
Laravel 8

**Comment by Acathon** [comment]
> @brioapp could you provide sample code ?
// controller
`$avatar->create('First Last')->setTheme(['colorful', 'grayscale-dark']);`

and always is generating the same color..

//avatar.php
 // List of theme name to be used when rendering avatar
    // Possible values are:
    // 1. Theme name as string: 'colorful'
    // 2. Or array of string name: ['grayscale-light', 'grayscale-dark']
    // 3. Or wildcard "*" to use all defined themes
    'theme' => ['*'],

**Comment by JeffreyBool** [comment]
Use the following method

```php
use Laravolt\Avatar\Avatar;

// create your first avatar
$avatar = new Avatar($config);
$avatar->create('John Doe')->toBase64();
$avatar->create('John Doe')->save('path/to/file.png', $quality = 90);
```
