### ISSUE TITLE
config is empty when using facade 

### ISSUE THREAD

**Issue by Orest-Divintari** [laravolt/avatar#127]
When I use the ```Avatar``` facade to create an image, I get always the same background colour, even if I change usernames, the background colour is always grey.

However if I don't use the facade but instead I instantiate the ```Avatar``` class and pass the config in the constructor then it works properly and I get different background colour based on the given username.

```
$config = config('laravolt.avatar');
$avatar = new Avatar($config);
```

I have ```Laravel 7.13.0``` installed.
I tried to manually register the service provider and alias but it didn't help.

```
Laravolt\Avatar\ServiceProvider::class,

'Avatar'    => Laravolt\Avatar\Facade::class,
```

**Comment by uyab** [comment]
Could you check if the latest version (4.1.4) still have problem with that?
Where do you call `Avatar` facade ?
