### ISSUE TITLE
Arabic (utf8) not working

### ISSUE THREAD

**Issue by balin09** [laravolt/avatar#129]
The package work with English only same problem [#69 ](https://github.com/laravolt/avatar/issues/69) and [#58 ](https://github.com/laravolt/avatar/issues/58) i try to set custom Arabic font i used  setFont method and i changed path in avatar.php but it doesn't work any help pls
I used the last version 4.1.4

**Comment by uyab** [comment]
@balin09 could you provide some sample code?

**Comment by balin09** [comment]
@uyab here some code
avatar.php:


`
    'driver' => env('IMAGE_DRIVER', 'gd'),

    // Initial generator class
    'generator' => \Laravolt\Avatar\Generator\DefaultGenerator::class,

    // Whether all characters supplied must be replaced with their closest ASCII counterparts
    'ascii'    => false,

    // Image shape: circle or square
    'shape' => 'square',

    // Image width, in pixel
    'width'    => 100,

    // Image height, in pixel
    'height'   => 70,

    // Number of characters used as initials. If name consists of single word, the first N character will be used
    'chars'    => 2,

    // font size
    'fontSize' => 38,

    // convert initial letter in uppercase
    'uppercase' => true,

    'rtl' => false,

    // Fonts used to render text.
    // If contains more than one fonts, randomly selected based on name supplied
    'fonts' => [__DIR__ . '/../fonts/Tajawal-Medium.ttf'],

    // List of foreground colors to be used, randomly selected based on name supplied
    'foregrounds' => [
        '#FFFFFF',
    ],
...
`
call avatar

`img class="rounded-full" src="{{ Avatar::create($rating->user['fname'].$rating->user['lname'])->toBase64() }}"  alt="User image"
`


and here the ouptput:

![Capture d’écran 2021-09-02 131057](https://user-images.githubusercontent.com/43583431/131841238-53a361b0-4bd9-461a-934f-95b02badb5fe.png)

**Comment by balin09** [comment]
anyone try this plugin and worked with Arabic language ?

**Comment by uyab** [comment]
I downloaded (hopefully) the same font from https://www.fontpalace.com/font-download/tajawal-medium/ and its just works as expected.
![image](https://user-images.githubusercontent.com/149716/131928087-5eb1f615-662b-4986-8089-011f935165e4.png)

Can you validate if you have setup the fonts path correctly? Something like `dd(config('laravolt.avatar.fonts'))` and see if the output was correct.

**Comment by balin09** [comment]
@uyab so sorry for my late response 
here my output and i also try an online font link but it didint work

![image](https://user-images.githubusercontent.com/43583431/132097939-d1e73290-5369-4b3d-a5b4-8db2b4e1376a.png)

**Comment by balin09** [comment]
@uyab So sorry for late response
my bad i get confused with font path in avatar.php i thought it was correct ...
Thanxs.

**Comment by balin09** [comment]
@uyab 
So sorry for late response
my bad i get confused with font path in avatar.php i thought it was correct ..., now it worked fine when i change it.
but now i have an other problem: with arabic name it take 2 initial from first name only, exp for ( Imad Abd ) i expect [I A] but i get [Im]. it work with english fine, and thats with rtl -> true.

**Comment by uyab** [comment]
You can create your own InitialGenerator class. Please check the configuration file.
