### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by fun4life1990** [laravolt/avatar#133]
Currently I can't update to Laravel 9 because of usage laravolt/avatar
As I see there is no Laravel breaking changes found in your code, so it should be pretty easy

**Comment by uyab** [comment]
New version will be tagged after Laravel 9 officially released on packagist. Meanwhile, you can use laravolt/avatar `dev-master`.

**Comment by khaledelmahdi** [comment]
Laravel 9 officially released, could you please tag the new version 😇?

**Comment by OryzonGroup** [comment]
Hello can you mark the version with laravel 9 support

**Comment by uyab** [comment]
Tagged: https://github.com/laravolt/avatar/releases/tag/4.1.6
