### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by wayahnawe** [laravolt/avatar#137]
Using $this when not in object context:
![image](https://user-images.githubusercontent.com/5630952/192152920-d5af9538-2baa-478e-b19e-79138695d696.png)

**Comment by uyab** [comment]
Please make sure you import the correct Facade class

**Comment by shlucky90** [comment]
> Using $this when not in object context: ![image](https://user-images.githubusercontent.com/5630952/192152920-d5af9538-2baa-478e-b19e-79138695d696.png)

use Laravolt\Avatar\Facade as Avatar;
