### ISSUE TITLE
The create() Non-static method

### ISSUE THREAD

**Issue by liuyami** [laravolt/avatar#14]
Laravel 5.2.

error message:
>Non-static method Laravolt\Avatar\Avatar::create() should not be called statically, assuming $this from incompatible context

**Comment by uyab** [comment]
You should call it via alias `\Avatar::create()`:

Assumed you already add code below to `config.php`:
```php
'Avatar'    => Laravolt\Avatar\Facade::class,
```

**Comment by liuyami** [comment]
Thank you very much, the problem has been resolved.@uyab

**Comment by anuzbvbmaniac** [comment]
> 
> 
> You should call it via alias `\Avatar::create()`:
> 
> Assumed you already add code below to `config.php`:
> 
> ```
> 'Avatar'    => Laravolt\Avatar\Facade::class,
> ```

I have this error.
```
Class name must be a valid object or a string 
```

Thank you in advance for help

**Comment by Rithwanul** [comment]
I am getting the same error

**Comment by uyab** [comment]
@Rithwanul Did you try https://github.com/laravolt/avatar/issues/14#issuecomment-177506093 ?
