### ISSUE TITLE
Error using in Laravel Framework 9.47.0, Please help !!!

### ISSUE THREAD

**Issue by algobasket** [laravolt/avatar#141]
Configure on config/app
![image](https://user-images.githubusercontent.com/8275673/212645231-d79fa99b-47c1-4ccc-a777-1ea54ca1ca29.png)
![image](https://user-images.githubusercontent.com/8275673/212645531-9d55e28c-165b-45f3-b5a8-dbcde7052099.png)
![image](https://user-images.githubusercontent.com/8275673/212645628-f997b646-baf3-43c5-9fff-f64eeeac0ffa.png)

**Comment by renky** [comment]
You don't use the Facade - you imported that Avatar Class itself...

just remove the use Laravolt\Avatar\Avatar from line 9 and call it like so in line 17:
$test = \Avatar::create.....
