### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by zajinx** [laravolt/avatar#143]
Please add support for Laravel 10.
Thank you.

**Comment by websitevirtuoso** [comment]
Yes waiting it. ASAP.
php8.2 as well

**Comment by dambridge** [comment]
Based on activity, it may be time to either fork or move to something like https://ui-avatars.com.

**Comment by uyab** [comment]
Working on it

**Comment by dambridge** [comment]
Awesome!

**Comment by uyab** [comment]
Sorry, it will take longer than I expected. `intervention/image` still having issue with PHP 8.1: https://github.com/Intervention/image/issues/1178

**Comment by renky** [comment]
Maybe it is time to switch... the last release of intervention/image is from August 2022 and it is an alpha-version - over 300 open issues... https://github.com/Intervention/image/issues/1193

**Comment by francoism90** [comment]
Any update on this? Seems this is the only package stopping from upgrading to L10.

Thanks!

**Comment by francoism90** [comment]
https://github.com/spatie/laravel-glide

Would this be an option?

**Comment by dambridge** [comment]
I'm using ui-avatars in the interim until we see how it all plays out.

**Comment by uyab** [comment]
https://github.com/laravolt/avatar/releases/tag/5.0.0

**Comment by seebeen** [comment]
Is anyone here willing to fork and rework the @intervention/image repo?

**Comment by francoism90** [comment]
@seebeen You should check out alternatives like https://github.com/spatie/image
