### ISSUE TITLE
Upgrade to intervention/image:^3.0

### ISSUE THREAD

**Issue by nickfls** [laravolt/avatar#150]
I know the API changed dramatically for the intervention/image:^3.0
Shall we commence the work to identify all necessary changes to bring it up to speed?

**Comment by uyab** [comment]
@nickfls any idea or pull request are welome.

**Comment by padre** [comment]
Does anyone have any news on this? Thanks!

**Comment by marceloarklok** [comment]
Does anyone have a deadline for this change? I really need to use version 3 of intervention/image and I don't want to abandon laravolt/avatar
