### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by rosemalejohn** [laravolt/avatar#154]
Timeline for Laravel 11 support?

**Comment by cytech** [comment]
i see it is in dev-master.
can we get a release published?

**Comment by giddy77** [comment]
Taking quite sometime, Just realized it's the only one preventing my project upload right now. lol

**Comment by uyab** [comment]
https://github.com/laravolt/avatar/releases/tag/5.1.0 , can someone verify if this newly tagged version work smoothly with Laravel 11 ?

**Comment by giddy77** [comment]
> https://github.com/laravolt/avatar/releases/tag/5.1.0 , can someone verify if this newly tagged version work smoothly with Laravel 11 ?

Yeah, works fine

**Comment by cytech** [comment]
all good here. works fine.
thanx

**Comment by darkwolf1812** [comment]
I tried to install in Laravel 11, but I have Intervention lib in the 3.6.3 version.
I couldn´t install..
Any help?

**Comment by uyab** [comment]
Please follow the issue about Intervention 3 here:
https://github.com/laravolt/avatar/issues/150
