### ISSUE TITLE
[Feature] Allow direct access to Image object

### ISSUE THREAD

**Issue by spaceemotion** [laravolt/avatar#16]
I recently stumbled upon your package and finally was able to try it out. As we're using VueJS for our backend and user lists we cannot use the inline base64 or to PNG file feature.

Looking at the documentation for the Image library you're using I would have to use its ```response('png')``` call to properly use it in our case (custom route taking the desired user ID). As you locked all the methods and properties I had to use reflection for the time being:

```php
public function avatar($userId) {
	$avatar = \Avatar::create(User::findOrFail($userId)->present()->name)
		->setFontSize(32)
		->setShape('square')
		->setBorder(0, 'transparent')
		->setDimension(75, 75);

	// Due to limitations of the package we need to build the image manually here
	$reflector = new \ReflectionObject($avatar);

	$method = $reflector->getMethod('buildAvatar');
	$method->setAccessible(true);
	$method->invoke($avatar);

	$imageField = $reflector->getProperty('image');
	$imageField->setAccessible(true);
	return $imageField->getValue($avatar)->response('png');
}
```

This package meets perfectly our expectations but sadly does not offer this one feature. It would be nice to have a direct "buildImage" call to get the image object itself to further return it as a response. Hope the code above helps.

Cheers and keep it up!

**Comment by uyab** [comment]
I see, I think I gonna add a method to return the image object itself, something like `getImageObject()`, what do you think?

**Comment by spaceemotion** [comment]
Yes, that sounds perfect! Keep in mind that the image would have to be built before getting the image :)

**Comment by uyab** [comment]
Could you update the package to 1.3.0 and see if it is working?

**Comment by spaceemotion** [comment]
Yup that works, thanks ;)
