### ISSUE TITLE
doesnt print letters unless the first one is Capital.

### ISSUE THREAD

**Issue by ctf0** [laravolt/avatar#18]
its kinda limiting, is there an option to include into the config to enable / disable this feature ?

**Comment by uyab** [comment]
Hi @ctf0, do you use custom font ? May you copy your sample code here?

**Comment by ctf0** [comment]
yeap, i use 
https://www.myfonts.com/fonts/mti/rockwell/ & https://www.behance.net/gallery/7775793/Airbag-Typeface

all the settings for avatar are same as the default and the code for creating the avatar
`Avatar::create($user->username)->toBase64()`

the issue is that the package work is not consistant, like sometimes it would read the first 2 letters and another time it wont read anything at all , and if the username have spaces it would escape everything before the space `ex. xyz 123` u would get the **1** only, also if there was a dot in the name it will escape the whole thing.

**Comment by uyab** [comment]
I added your test case and run the test, it seems no problem at all. Would you like to remove the custom fonts and see if its works ?

**Comment by ctf0** [comment]
okay i think i found the one causing the issue, the Airbag font only supports capital letters, so when the package run and it chose that font , nothing comes out.
