### ISSUE TITLE
class Image not found

### ISSUE THREAD

**Issue by ctf0** [laravolt/avatar#21]
as this package is using intervention , so unless i add the provider and the facade for intervention to the app/config aswell , the class not found error keeps popping up  every now and then 😢

**Comment by uyab** [comment]
Are you already add both service providers?

**Comment by ctf0** [comment]
when i add the image service provider the issue is gone , but i think this is already being taken care of when i add the avatar class , right ?

**Comment by uyab** [comment]
As mentioned in the doc, you must add both SP:
```
Intervention\Image\ImageServiceProvider::class,
Laravolt\Avatar\ServiceProvider::class,
```

**Comment by ctf0** [comment]
oh, okay ,many thanx :+1:
