### ISSUE TITLE
How to set font?

### ISSUE THREAD

**Issue by iVanilla** [laravolt/avatar#24]
Hi.
My website is using Simplified Chinese, so many users will use Chinese username, I need to determine  the first character of username is Chinese, English(letters) or integer, and then decide which font to use, but your setFont() function don't have any parameters, What should I do?

**Comment by uyab** [comment]
Sorry, such a feature currently not available yet. But I think you have a valid example where these feature would be nice  to be implemented. Let me see if I can do it quickly.

**Comment by uyab** [comment]
https://github.com/laravolt/avatar/releases/tag/1.7.0, I hope this will fullfill what you need :)

**Comment by iVanilla** [comment]
@uyab Thanks.
