### ISSUE TITLE
Help :)

### ISSUE THREAD

**Issue by phaistonian** [laravolt/avatar#25]
I am new to all-things Composer and I am having a hard time making this work.

After installing by going `composer require laravolt/avatar` then I have this.

``` php
require '../../php/vendor/autoload.php';
echo Avatar::create('test')→toBase64();
```

I am getting all sorts of errors and for the life of me I can’t make it work, no matter what I tried.

Some help for the newbie?:)

Update:

I kind of figured it out, but here's where I am at now:

`Fatal error: Uncaught RuntimeException: A facade root has not been set. in vendor/illuminate/support/Facades/Facade.php`

**Comment by uyab** [comment]
Sorry, this package intended to be used within Laravel framework. I will take a look if it is possible to use it in any php project.

**Comment by phaistonian** [comment]
Thanks for the response @uyab.

This was driving me nuts :)
