### ISSUE TITLE
Uppercase all letters support

### ISSUE THREAD

**Issue by xcaptain** [laravolt/avatar#27]
Like my name is Joey, Now I will get Jo but I want to get JO. How about add a uppercase config so people can choose whether upcase all the letters.

**Comment by uyab** [comment]
Make sense, just wait a minute.

Meanwhile, you can pick a font that support only uppercase :)

**Comment by uyab** [comment]
New config `uppercase` added, default to false. Please update laravolt/avatar to newly tagged version 1.8.0.

**Comment by xcaptain** [comment]
Great job, thanks.
