### ISSUE TITLE
Uppercase doesn't work...

### ISSUE THREAD

**Issue by xoco70** [laravolt/avatar#28]
When I first generate app.php, it came without 

    'uppercase' => true,

I checked it in the github doc, and added it, but it is not working, still get it in lowercase.

Here is how I use it in my view:

`<img src="{!! Auth::getUser()->avatar ?? Avatar::create(Auth::getUser()->email)->toBase64() !!}">`

**Comment by uyab** [comment]
What font do you used?

**Comment by xoco70** [comment]
"Open Sans", Helvetica Neue, Helvetica, Arial, sans-serif

And I use 

Avatar::create(Auth::getUser()->email)->toBase64()

to create it

**Comment by uyab** [comment]
Can you show how exactly your avatar config file look like?

**Comment by xoco70** [comment]
yep, no problem:


`
<?php
/*
 * Set specific configuration variables here
 */
return [
    // Whether all characters supplied must be replaced with their closest ASCII counterparts
    'ascii'    => false,
    'uppercase' => true,

    // Image shape: circle or square
    'shape' => 'circle',

    // Image width, in pixel
    'width'    => 100,

    // Image height, in pixel
    'height'   => 100,

    // Number of characters used as initials. If name consists of single word, the first N character will be used
    'chars'    => 1,

    // font size
    'fontSize' => 48,



    // Fonts used to render text.
    // If contains more than one fonts, randomly selected based on name supplied
    // You can provide absolute path, path relative to folder resources/laravolt/avatar/fonts/, or mixed.
    'fonts'    => ['OpenSans-Bold.ttf', 'rockwell.ttf'],

    // List of foreground colors to be used, randomly selected based on name supplied
    'foregrounds'   => [
        '#FFFFFF',
    ],

    // List of background colors to be used, randomly selected based on name supplied
    'backgrounds'   => [
        '#f44336',
        '#E91E63',
        '#9C27B0',
        '#673AB7',
        '#3F51B5',
        '#2196F3',
        '#03A9F4',
        '#00BCD4',
        '#009688',
        '#4CAF50',
        '#8BC34A',
        '#CDDC39',
        '#FFC107',
        '#FF9800',
        '#FF5722',
    ],

    'border'    => [
        'size'  => 1,

        // border color, available value are:
        // 'foreground' (same as foreground color)
        // 'background' (same as background color)
        // or any valid hex ('#aabbcc')
        'color' => 'foreground',
    ],
];
`

**Comment by uyab** [comment]
Can you confirm that you have installed laravolt/avatar version 1.8.0 (https://github.com/laravolt/avatar/releases/tag/1.8.0) ?

**Comment by xoco70** [comment]
This was the issue! Installed it for 5.1! Txxx
