### ISSUE TITLE
What goodies am I missing from 1.*?

### ISSUE THREAD

**Issue by rzb** [laravolt/avatar#30]
I'm on L5.1 and can't upgrade anytime soon. I'd be nice to know what features I'm missing. 

Thank you for your work.

**Comment by uyab** [comment]
Hi @rzb, glad to know that this package useful for your project. 
Actually there is no major feature addition in 1.x, just several enhancement like `auto uppercase`, `create avatar from email`, and more `unit test`.

If you find version `0.x` still fit for your project, it is ok to stick with it.
