### ISSUE TITLE
Unable to set font at runtime

### ISSUE THREAD

**Issue by rzb** [laravolt/avatar#31]
On 0.3.3, `setFont()` is a protected, unchainable, no-argument function.

**Comment by uyab** [comment]
sorry, 0.x no longer maintained, please use version 1.x

**Comment by renatoslcdevshop** [comment]
Ok. Then please remove L5.1 support from the readme or add a "use at your own risk" note.

Thanks for the package.

**Comment by rzb** [comment]
Ok. Then please remove L5.1 support from the readme or add a "use at your own risk" note.

Thanks for the package.
