### ISSUE TITLE
Reverse Initials

### ISSUE THREAD

**Issue by mintzs** [laravolt/avatar#38]
Thanks for the great package!

I was wondering if you could add a config flag to reverse the initials, so for example, John Doe's avatar would be (DJ) instead of (JD).

Thanks :)

**Comment by uyab** [comment]
It was easy to implement, but I don't think this was common needs. Could you explain more why you need this?

**Comment by mintzs** [comment]
Yes, RTL languages get the initials in reverse order...

**Comment by uyab** [comment]
For "Andy Bar Cook" as a name and initial length was `2`, which one do you expects as initials? `BA` or `CB`

**Comment by mintzs** [comment]
As for RTL languages "Cook" would be the first name, "Bar" the middle name and "Andy" the last name, therefore, to work similar to LTR languages, I would expect `CB`.

I would also appreciate if you would add the reverse functionality as a dynamic call, not just as a config flag, due to the fact that the code has to first determine whether the input string is RTL or LTR and then use (or not) the reverse mode.

Thanks again :)

**Comment by uyab** [comment]
Yes, I'm thinking the same about customizable InitialGenerator class. In the meantime, you can just generate your own initials, and pass the final string to avatar class :)

**Comment by uyab** [comment]
Hi @mintzs, would you like to check master branch to see if current implementation can fulfill your needs?

**Comment by mintzs** [comment]
Great! This way I can extend the default generator class, check the string and manipulate it if necessary before calling the original `make` method (using `parent::make`).

*Of course, for my specific case I'd check the string's direction and if RTL would reverse the string prior to the parent `make `call.
