### ISSUE TITLE
Public config changes not effecting

### ISSUE THREAD

**Issue by imtiazwazir** [laravolt/avatar#45]
<img width="394" alt="screen shot 2017-08-27 at 12 04 12 am" src="https://user-images.githubusercontent.com/1964969/29744287-70126fc0-8abb-11e7-83fa-73f4d5508ad1.png">
<img width="404" alt="screen shot 2017-08-27 at 12 04 38 am" src="https://user-images.githubusercontent.com/1964969/29744286-6ffa276c-8abb-11e7-87f4-231ae1f0cfde.png">

Changes in public config "config/laravolt/avatar.php" not effecting - any reason why?

**Comment by uyab** [comment]
Which version did you use?

**Comment by robindirksen1** [comment]
Same problem here.

**Comment by uyab** [comment]
@robindirksen1 can you provide more valuable information: which version did you use, code snippet when generating avatar, and dump result from calling `dd(config("laravolt.avatar"))`.

**Comment by robindirksen1** [comment]
dd(config("laravolt.avatar"));

```
array:13 [▼
  "driver" => "gd"
  "generator" => "Laravolt\Avatar\Generator\DefaultGenerator"
  "ascii" => false
  "shape" => "square"
  "width" => 1000
  "height" => 1000
  "chars" => 2
  "fontSize" => 500
  "uppercase" => false
  "fonts" => array:2 [▶]
  "foregrounds" => array:1 [▼
    0 => "#FFFFFF"
  ]
  "backgrounds" => array:15 [▼
    0 => "#f44336"
    1 => "#E91E63"
    2 => "#9C27B0"
    3 => "#673AB7"
    4 => "#3F51B5"
    5 => "#2196F3"
    6 => "#03A9F4"
    7 => "#00BCD4"
    8 => "#009688"
    9 => "#4CAF50"
    10 => "#8BC34A"
    11 => "#CDDC39"
    12 => "#FFC107"
    13 => "#FF9800"
    14 => "#FF5722"
  ]
  "border" => array:2 [▼
    "size" => 1
    "color" => "foreground"
  ]
]
```

To create avatar:
```
<img src="{{ $a->create(Auth::user()->name)->toBase64() }}" class="changeable">
```

AppServiceProvider.php
```
public function boot()
    {
        Schema::defaultStringLength(191);

        $a = new Avatar();
        View::share('a', $a);
    }
```

**Comment by uyab** [comment]
Ah, so you are instantiate Avatar class manually, instead of using Facade. If that is what you want, you can take a look how `Avatar` internally created:

https://github.com/laravolt/avatar/blob/master/src/ServiceProvider.php#L25-L28

You need to pass config too.

Just curious, why dont you use register the alias `'Avatar'    => Laravolt\Avatar\Facade::class` so you can call it in view like this (just as documented):

`Avatar::create('Joko Widodo')->toBase64();`

**Comment by robindirksen1** [comment]
I tried but that it says the follow:

`Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Non-static method Laravolt\Avatar\Avatar::create() should not be called statically`

**Comment by robindirksen1** [comment]
Okay, it works. I removed `Laravolt\Avatar\`, forgot that it is assign as a Facade.

`Avatar::create(Auth::user()->name)->toBase64()`

**Comment by sarthaksavvy** [comment]
use config in avatar class,
$avatar = new Avatar(config('laravolt.avatar'));
then use $avatar->create($name)->toBase64();

**Comment by uyab** [comment]
Thanks @sarthaksavvy , that sholud works if you dont use Laravel Facade
