### ISSUE TITLE
Composer require fails installation

### ISSUE THREAD

**Issue by NotHolst** [laravolt/avatar#47]
```
> @php artisan package:discover


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required 'C:\Github\project\vendor\laravolt\avatar\src/../config/config.php' (include_path='.;C:\php\pear')


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json to its original content.
```

I have no idea why this is happening

**Comment by uyab** [comment]
Hmm, I think it is related to directory separator. The path produced contains mixed char `\` and`/`, which is I'm sure only happen in Windows. 

Can you check whether path `C:\Github\project\vendor\laravolt\avatar\src/../config/config.php` is valid or not? Maybe using something like `is_file` or `is_exists`.

**Comment by NotHolst** [comment]
It seems to work now, just repeated the exact same steps as i did on my laptop, but it seems to work on my desktop for some reason :)
