### ISSUE TITLE
Config file inside a folder?

### ISSUE THREAD

**Issue by Cannonb4ll** [laravolt/avatar#49]
Is there a specific reason why the config file is being published inside the config/laravolt folder? It does not seem necessary to be honest and makes the structure look ugly.

I would rather have all my config files displayed at once, once I open up the config folder tree.

**Comment by uyab** [comment]
Because initially this package was part of **laravolt** vendor, which is consist of several packages. It is easier for me if all config placed in one location. 

Second, `avatar` was general name, place it directly in config folder increase the chances of naming collission with other package.
