### ISSUE TITLE
Can't install with Laravel 5.1

### ISSUE THREAD

**Issue by CptChaos** [laravolt/avatar#5]
I am getting an error while trying to install your Avatar package through composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: danielstjules/stringy[2.2.0, 1.10.0].
    - Can only install one of: danielstjules/stringy[2.2.0, 1.10.0].
    - Can only install one of: danielstjules/stringy[2.2.0, 1.10.0].
    - laravolt/avatar 1.2.0 requires danielstjules/stringy ~2.2 -> satisfiable by danielstjules/stringy[2.2.0].
    - Installation request for laravolt/avatar ^1.2 -> satisfiable by laravolt/avatar[1.2.0].
    - Installation request for danielstjules/stringy == 1.10.0.0 -> satisfiable by danielstjules/stringy[1.10.0].
```

The required package Stringy also can't be installed on a Laravel 5.1 system.
Or should I install both Stringy 1.10.0 and 2.2.0?

**Comment by uyab** [comment]
For Laravel 5.1, you should use laravolt/avatar version 0.3.

**Comment by uyab** [comment]
Documentation updated.

**Comment by DeeJaVu** [comment]
i have the same error using upgraded laravel 5.1 to 5.2

**Comment by uyab** [comment]
@DeeJaVu which avatar version did you use?

**Comment by DeeJaVu** [comment]
i did  composer require laravolt/avatar

**Comment by uyab** [comment]
Can you provide your composer.json entries ?

**Comment by DeeJaVu** [comment]
its fixed !

i had `"laravolt/avatar": "^1.2"` in my composer.json

i did composer update and it deleted 
```
danielstjules/stringy (1.10.0)
Removing laravolt/avatar (0.3.0)
```
then i  succesfully ran composer require laravolt/avatar

sorry for taking your time, i had to look in to composer file in the first place.
