### ISSUE TITLE
SVG generation looks off in firefox

### ISSUE THREAD

**Issue by laravelian** [laravolt/avatar#55]
![image](https://user-images.githubusercontent.com/1485635/37296718-2a559f02-25f2-11e8-856c-b41a62a0276c.png)

This was a file saved with the ->toSvg() method with default settings.  The avatar looks fine in all other browsers I have tried (Chrome & Safari)

**Comment by thesimpledesigners** [comment]
it's due to the "y" attribute in the `<text y="value">RM</text> `
it's calculating the center from the bottom of the text 
![image](https://user-images.githubusercontent.com/9967336/39969923-09032184-56db-11e8-86fc-e6851c4eda4b.png)
can't find a proper solution to fix it
