### ISSUE TITLE
Commendation

### ISSUE THREAD

**Issue by samalapsy** [laravolt/avatar#57]
Wow this library is really wonder. Thumbs up to  @uyab ; more grease to your elbow. 

Please can you kindly work on the image quality too. This is a 70x70 image with fontsize 25px Using toBase64().   The quality is poor.
![opera snapshot_2018-05-29_174539](https://user-images.githubusercontent.com/13020916/40672954-3f63e80a-6368-11e8-9869-55cc45cf6111.png)

## Once again you've really done  a nice job 

# **THANK YOU**

**Comment by uyab** [comment]
Hi @samalapsy, you can set `driver` to imagick for better result. Or maybe generate larger image and display it on small size. Currently I don't have any idea how to smoothing the border using GD library.
