### ISSUE TITLE
Class image does not exist

### ISSUE THREAD

**Issue by randyrankin** [laravolt/avatar#6]
Receive error message: Class image does not exist. 

Using Laravel 5.2

**Comment by PJijin** [comment]
Same error. Laravel 5.2
ErrorException in Container.php line 738: Class image does not exist

**Comment by randyrankin** [comment]
This seems to have been corrected by adding Intervention\Image\ImageServiceProvider::class as a service provider and Intervention\Image\ImageServiceProvider::class as an alias in app.php.

**Comment by uyab** [comment]
Yes, we must add `Intervention\Image\ImageServiceProvider::class` as a providers too. Documentation updated.
