### ISSUE TITLE
Call to undefined function Intervention\Image\Gd\imagettfbbox()

### ISSUE THREAD

**Issue by RikyBordo** [laravolt/avatar#62]
Hello,

This is error:

<img width="524" alt="screen shot 2018-06-30 at 15 24 07" src="https://user-images.githubusercontent.com/40716719/42125623-d963689c-7c7a-11e8-8e95-77aa46c7b54a.png">

This is my phpinfo(), GD table:

<img width="411" alt="screen shot 2018-06-30 at 15 23 42" src="https://user-images.githubusercontent.com/40716719/42125610-a6aad066-7c7a-11e8-9e75-4e5516a15bcb.png">

I'm using Laravel 5.6 and MAMP PRO 4.3 with PHP 7.1.12 for my localhost

**Comment by uyab** [comment]
Please see https://github.com/Intervention/image/issues/484

**Comment by jasonmonroe** [comment]
I'm having this issue as well but with Laravel v5.2.45.
