### ISSUE TITLE
Does this work with ImageMagick?

### ISSUE THREAD

**Issue by ronnyandre** [laravolt/avatar#7]
I get an error trying to use `Avatar::create($user->name)->toBase64()` I get presented with the following error message:

```
FatalErrorException in Font.php line 85:
Call to undefined function Intervention\Image\Gd\imagettfbbox()
```

Is it possible to use with ImageMagick?

**Comment by uyab** [comment]
Internally, this library utilize [intervention](http://image.intervention.io/getting_started/installation), and it is support GD or Imagick. 
You can publish intervention configuration by following command:
`php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"`
and then change driver from GD to imagick.

**Comment by uyab** [comment]
Or maybe [this issue](https://github.com/Intervention/image/issues/484) relevant to your case.
