### ISSUE TITLE
Class 'Avatar' not found

### ISSUE THREAD

**Issue by DevChristians** [laravolt/avatar#72]
Hey there! 
i've a problem with this 'Avatar'
My version of laravel is 5.3, I do not know if there is a bug for this.

> BUG
![Captura de pantalla de 2019-03-15 15-19-01](https://user-images.githubusercontent.com/27924062/54456809-1ce3ad80-4736-11e9-81a3-98083de9e2c0.png)

> My controller part 1
![Captura de pantalla de 2019-03-15 15-23-09](https://user-images.githubusercontent.com/27924062/54456886-4ef50f80-4736-11e9-8b45-67884ce72600.png)

> My controller part 2
![Captura de pantalla de 2019-03-15 15-37-07](https://user-images.githubusercontent.com/27924062/54457594-3685f480-4738-11e9-8ae5-264c3f87c082.png)

>Provider and aliase
![Captura de pantalla de 2019-03-15 15-54-23](https://user-images.githubusercontent.com/27924062/54458613-c75dcf80-473a-11e9-9ca3-66618ccb1ddd.png)
![Captura de pantalla de 2019-03-15 15-54-27](https://user-images.githubusercontent.com/27924062/54458627-d47abe80-473a-11e9-9152-afbe6f31368d.png)

> Composer.json
![Captura de pantalla de 2019-03-15 15-58-50](https://user-images.githubusercontent.com/27924062/54458829-50750680-473b-11e9-8e51-dacf44589444.png)

Any suggestions? thanks!

**Comment by uyab** [comment]
Hi, maybe you need to run `composer dump-autoload` and/or `php artisan clear-compiled`.

**Comment by DevChristians** [comment]
@uyab Thanks so much!! for real men <3
