### ISSUE TITLE
Text vertical alignment issue with imagick and toBase64

### ISSUE THREAD

**Issue by knoufal** [laravolt/avatar#76]
Had to switch to imagick for better image quality but now text is not aligned properly inside the icon with **toBase64**, text was aligned correctly with GD Library without any issues. I am using an Arabic font.

![Image of Avatar](https://i.ibb.co/n1DDdYV/laravolt.png)

Thanks :)

**Comment by marooj** [comment]
on 
vendor\laravolt\avatar\src\Avatar.php
line 394 
change 
$y = $this->height / 2;
to 
$y = $this->height / 3;

**Comment by aaronhuisinga** [comment]
Having this same issue using the default font and just returning as a response. GD works without issue.

**Comment by uyab** [comment]
Probably related issue: https://github.com/avalanche123/Imagine/issues/32

**Comment by danpalmieri** [comment]
has anyone solved?
