### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by arnebr** [laravolt/avatar#77]
On the latest update I got the following error: 
````
*******************************************
 /!\ Warning, you're using a deprecated
 ¨¨¨ version of Carbon, we will soon stop
     providing support and update for 1.x
     versions, please upgrade to Carbon 2.
*******************************************

Most features of Carbon 1 are still available in Carbon 2.
See how to migrate: https://carbon.nesbot.com/docs/#api-carbon-2

You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
````

This error is because an old version of `illuminate/support` is used. A fix by the author of the package was already provided. 
Would be awesome, if we can update the dependencies.

Since I can´t test it at the moment, I can´t open a pull request for now.

**Comment by uyab** [comment]
Thank you for reporting. What Laravel version do you use?

**Comment by arnebr** [comment]
@uyab none, I use the libary as a standalone component.

**Comment by uyab** [comment]
You can upgrade carbon to latest version `require nesbot/carbon:^2.0`
