### ISSUE TITLE
Laravel 6.0 Support?

### ISSUE THREAD

**Issue by jjhamkuijpers** [laravolt/avatar#78]
Would it be able to support Laravel ^6.0?

**Comment by uyab** [comment]
Yes, hope I can release new version soon after L6 released.

**Comment by neoteknic** [comment]
It's out ! Maybe just libs to update ?

**Comment by neoteknic** [comment]
Working with dev-master thank you ! Can you make a release ?

**Comment by uyab** [comment]
@neoteknic I will tagged new version (3.0.0) in the next several hours.
