### ISSUE TITLE
setdimension() not working

### ISSUE THREAD

**Issue by padre** [laravolt/avatar#79]
The method setdimension() not working. The generated image always has the size 100x100

For example:

Avatar::create('Habibie')->setDimension(50)->setFontSize(18)->toBase64() has the size 100x100

**Comment by Hirbod** [comment]
I can confirm this

**Comment by Hirbod** [comment]
@padre are you also on Laravel 6.* by any chance? It looks like I am also getting troubles with config files since I've upgraded

**Comment by Hirbod** [comment]
@laravolt Not a single method works for me. Everything comes out like trash, wasn't before I updated.. 
![K0nzwe1j_avatar](https://user-images.githubusercontent.com/504909/68628936-5d244700-04e2-11ea-9cce-15c0736bcf99.jpg)


It is ignoring every single setting.

```
        $avatar = Avatar::create($user->name)
            ->setDimension(1000, 1000)
            ->setShape('square')
            ->setFontSize(50)
            ->getImageObject()
            ->encode('jpg');

        // store image
        Storage::put('public/' . $user->avatar, (string) $avatar);
```

**Comment by padre** [comment]
@Hirbod yes, on Laravel 6. On laravel 5 all methods worked.

**Comment by Hirbod** [comment]
Yeah, same for me @padre. Since I am lucky and I only need one global config, I set everything under config/laravolt/config.php - its working from there, but I think something need to be changed for Laravel 6.*

**Comment by uyab** [comment]
Please check if https://github.com/laravolt/avatar/releases/tag/3.0.1 works for you

**Comment by gekkedev** [comment]
> Please check if https://github.com/laravolt/avatar/releases/tag/3.0.1 works for you

I can confirm this is fixed in newer versions.
`composer update laravolt/avatar`
