### ISSUE TITLE
Can't composer install...

### ISSUE THREAD

**Issue by lauhakari** [laravolt/avatar#8]
From bash..

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: intervention/image[2.3.2, 2.3.5].
    - Can only install one of: intervention/image[2.3.5, 2.3.2].
    - Can only install one of: intervention/image[2.3.2, 2.3.5].
    - laravolt/avatar 1.2.0 requires intervention/image 2.3.2 -> satisfiable by intervention/image[2.3.2].
    - Installation request for laravolt/avatar ^1.2 -> satisfiable by laravolt/avatar[1.2.0].
    - Installation request for intervention/image == 2.3.5.0 -> satisfiable by intervention/image[2.3.5].

**Comment by lauhakari** [comment]
Sorry for the short message, I was in a rush leaving work.

So the issue is (or was) that doing "composer require laravolt/avatar" gave me the error above.
When composer inserts it into the json file it adds it with version ^1.2. Searched a bit, found some tips and when I manually added it again to composer.json but as "laravolt/avatar": "~1.2" - then all seems to have worked.

So this is solved, but maybe something that can be controlled from the packages side?

**Comment by uyab** [comment]
Thank you for reporting, I have changed composer version for intervention/image to `^2.1` so it should more flexible when dealing with intervention/image.
