### ISSUE TITLE
Avatar not taking any config parameters

### ISSUE THREAD

**Issue by SiliconMachine** [laravolt/avatar#85]
I've installed the module and tried to pass parameters to customize the avatar as follows:

`use Laravolt\Avatar\Facade as Avatar;`

` $avatar = Avatar::create($user->name)->setDimension(280)->setShape('square')->getImageObject()->encode('png');`

dd(config("laravolt.avatar"));

`
array:16 [▼
  "driver" => "imagick"
  "generator" => "Laravolt\Avatar\Generator\DefaultGenerator"
  "decorator" => "Laravolt\Avatar\Theme\Decorator"
  "ascii" => false
  "shape" => "circle"
  "width" => 100
  "height" => 100
  "chars" => 2
  "fontSize" => 80
  "uppercase" => false
  "fonts" => array:2 [▼
    0 => "/var/www/config/laravolt/../fonts/OpenSans-Bold.ttf"
    1 => "/var/www/config/laravolt/../fonts/rockwell.ttf"
  ]
  "foregrounds" => array:1 [▼
    0 => "#FFFFFF"
  ]
  "backgrounds" => array:15 [▼
    0 => "#f44336"
    1 => "#E91E63"
    2 => "#9C27B0"
    3 => "#673AB7"
    4 => "#3F51B5"
    5 => "#2196F3"
    6 => "#03A9F4"
    7 => "#00BCD4"
    8 => "#009688"
    9 => "#4CAF50"
    10 => "#8BC34A"
    11 => "#CDDC39"
    12 => "#FFC107"
    13 => "#FF9800"
    14 => "#FF5722"
  ]
  "border" => array:2 [▼
    "size" => 1
    "color" => "background"
  ]
  "theme" => array:1 [▼
    0 => "*"
  ]
  "themes" => array:3 [▼
    "grayscale-light" => array:2 [▶]
    "grayscale-dark" => array:2 [▶]
    "colorful" => array:2 [▶]
  ]
]
`

Is not taking any parameters. It only works if I change the config file.

**Comment by uyab** [comment]
Please check if https://github.com/laravolt/avatar/releases/tag/3.0.1 works for you
