### ISSUE TITLE
Custom fonts not set

### ISSUE THREAD

**Issue by Release88** [laravolt/avatar#86]
When changing fonts in config, with command Avatar::create('NAME')->toBase64() doesn't set custom fonts, because fonts are set during __construct() function , when the $name attribute is not set. Then, when during the construct it tries to set custom fonts (with $this->getRandomFont() in applyTheme method), the getRandomElement called by getRandomFont() checks if the $name attribute is set ( if (strlen($this->name) == 0 || count($array) == 0) { ...)
the attribute, during the __construct() function, is not set, because is filled only with the create function, so the custom fonts will never be set.

**Comment by uyab** [comment]
Hi @Release88 , thank you for your report. Which version do you use?

**Comment by Release88** [comment]
Hi @uyab , i have "laravolt/avatar": "^3.0" in my composer.json

**Comment by uyab** [comment]
Can you update to latest version, 3.0.1, and check if this problem still exists?

**Comment by Release88** [comment]
It's already 3.0.1 version

**Comment by Release88** [comment]
Actually, to jump the problem, I have set statically the custom font file path in the Avatar.php file, through the construct method:

$this->defaultFont = resource_path() . '/fonts/Roboto-Light.ttf';

**Comment by uyab** [comment]
3.0.3 should fix this
