### ISSUE TITLE
empty circle

### ISSUE THREAD

**Issue by marooj** [laravolt/avatar#87]
text on circle not found on gd please help me

![Image of Yaktocat](http://uupload.ir/files/5uvd_avatar.png)

**Comment by marooj** [comment]
after change font in 
E:\PetroShop\vendor\laravolt\avatar\src\avatar.php
my problem solved
thank you please find problem

**Comment by marooj** [comment]
oh excuse me i am find problem 
problem is on Persian fonts after change it to 
`protected $defaultFont = __DIR__.'/../fonts/IRANSansWeb_Bold.ttf';`
 the Persian fonts supported .

**Comment by uyab** [comment]
Related to https://github.com/laravolt/avatar/issues/86

**Comment by uyab** [comment]
3.0.3 should fix this
