### ISSUE TITLE
Installing laravolt/avatar I got error method Laravolt\Avatar\Facade::isDeferred

### ISSUE THREAD

**Issue by sergeynilov** [laravolt/avatar#92]
Hello,
I tried to install /laravolt/avatar pluging in my laravel 6 app ana got error :

```
$ composer require laravolt/avatar
Using version ^3.0 for laravolt/avatar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing intervention/image (2.5.1): Loading from cache
  - Installing laravolt/avatar (3.0.6): Downloading (100%)         
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 149:
                                                                 
  Call to undefined method Laravolt\Avatar\Facade::isDeferred()  
                                                                
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

```
At https://github.com/laravolt/avatar  site I see last updates 5 days ago and it is niot absolute ?

composHello,
I tried to install /laravolt/avatar pluging in my laravel 6 app ana got error :

$ composer require laravolt/avatar
Using version ^3.0 for laravolt/avatar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing intervention/image (2.5.1): Loading from cache
  - Installing laravolt/avatar (3.0.6): Downloading (100%)         
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 149:
                                                                 
`  Call to undefined method Laravolt\Avatar\Facade::isDeferred()  
`                                                                
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

At https://github.com/laravolt/avatar  site I see last updates 5 days ago and it is not absolute ?

composer.json: 
```

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/helpers": "^1.1",
        "laravel/passport": "^8.1",
        "laravel/tinker": "^2.0",
        "laravolt/avatar": "^3.0"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "laravel/ui": "^1.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```
Why error and how to fix it ?

Thanks!
Why error and how to fix it ?

Thanks!

**Comment by uyab** [comment]
I cannot reproduce the issue with fresh Laravel install + `composer require laravolt/avatar`.

Maybe you can register ServiceProvider and Facade manually: https://github.com/laravolt/avatar#service-provider--facade

**Comment by sergeynilov** [comment]
Thanks!
