### ISSUE TITLE
Method Laravolt\Avatar\Avatar::__toString() must not throw an exception

### ISSUE THREAD

**Issue by Harsukh21** [laravolt/avatar#99]
i was used this package with laravel 7.
when i try to create image like that.
`<img src="{{ Avatar::create('S') }}" alt="S"> `
Error is :
Method Laravolt\Avatar\Avatar::__toString() must not throw an exception, caught Intervention\Image\Exception\NotSupportedException: ImageMagick module not available with this PHP installation.

Please help me.

**Comment by uyab** [comment]
Please refer to https://github.com/laravolt/avatar#configuration. You have two options:

1.  Install imagick extension, or
2. change the driver to `gd` (of course, you must make sure your server have php-gd extension)
